In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('model_performance_comparison.csv')
df.columns

Index(['model', 'mean_accuracy', 'std_accuracy', 'median_accuracy',
       'mean_balanced_accuracy', 'std_balanced_accuracy',
       'median_balanced_accuracy', 'mean_chance_balanced_accuracy',
       'std_chance_balanced_accuracy', 'median_chance_balanced_accuracy'],
      dtype='object')

In [16]:
def get_rounding(x:float):
    if x < 1 and x != 0:
        string = str(x)
        string = string.split('.')

        for i in range(len(string[1])):
            if i == len(string[1])-1:
                return i + 1

            elif string[1][i] != '0':
                if int(string[1][i+1]) >= 5 and string[1][i]=='9':
                    return i
                else: return i + 1
    else:
        return -len(str(int(np.round(x,0))))+1

def get_right_dec_figs_in_string(n,dec_places):
    dec_figs = len(str(n).split('.')[1])
    if dec_figs < dec_places:
        return str(n) + ''.join(['0']*(dec_places-dec_figs))
    else:
        return str(n)

def plus_minus(mean,std):
    std_dec_places = [get_rounding(x) if x!=0 else 0 for x in std]

    list_of_strings = []

    for x, y, z in zip(mean,std,std_dec_places):
        if y < 1 and y != 0:
            list_of_strings.append(f'{get_right_dec_figs_in_string(np.round(x,z),z)} ± {get_right_dec_figs_in_string(np.round(y,z),z)}')
        else:
            list_of_strings.append(f'{int(np.round(x,z))} ± {int(np.round(y,z))}')
    
    return list_of_strings

In [17]:
table = pd.DataFrame()

filter = ['(U)' not in x for x in df['model']]

table['Model'] = df[filter]['model']

# table['Mean Accuracy'] = plus_minus(df['mean_accuracy'],df['std_accuracy'])
# table['Median Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_accuracy'],2)]
table['Mean Balanced Accuracy [%]'] = plus_minus(df[filter]['mean_balanced_accuracy'],
                                             df[filter]['std_balanced_accuracy'])
# table['Median Balanced Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_balanced_accuracy'],2)]

table.T #.style.hide(axis="index")

,0,1,5,6,7,8,9,13,14,15,16
Model,DBCCR,Hybrid,KNN,GNB (W),Poly SVM (W),RBF SVM (W),3D MSCC,KNN (R-U),GNB (W) (R-U),Poly SVM (W) (R-U),RBF SVM (W) (R-U)
Mean Balanced Accuracy [%],60 ± 4,77 ± 3,86 ± 3,89 ± 2,92 ± 2,92 ± 2,83 ± 4,88 ± 4,90 ± 2,94 ± 2,93 ± 2

In [27]:
table = pd.DataFrame()

table['Model'] = df['model']

# table['Mean Accuracy'] = plus_minus(df['mean_accuracy'],df['std_accuracy'])
# table['Median Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_accuracy'],2)]
table['Mean Accuracy [%]'] = plus_minus(df['mean_accuracy'],
                                    df['std_accuracy'])
# table['Median Balanced Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_balanced_accuracy'],2)]

table.style.hide(axis="index")

In [19]:
df_pahs = pd.read_csv('model_performance_comparison_with_pahs.csv')

In [20]:
table = pd.DataFrame()

filter = ['(U)' not in x for x in df_pahs['model']]

table['Model'] = df_pahs[filter]['model']

# table['Mean Accuracy'] = plus_minus(df['mean_accuracy'],df['std_accuracy'])
# table['Median Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_accuracy'],2)]
table['Mean Balanced Accuracy [%]'] = plus_minus(df_pahs[filter]['mean_balanced_accuracy'],
                                             df_pahs[filter]['std_balanced_accuracy'])
# table['Median Balanced Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_balanced_accuracy'],2)]

table.T

                                 3        4             5            6
Model                          KNN  GNB (W)  Poly SVM (W)  RBF SVM (W)
Mean Balanced Accuracy [%]  88 ± 2   90 ± 2        93 ± 1       93 ± 2

In [21]:
table = pd.DataFrame()

table['Model'] = df_pahs['model']

# table['Mean Accuracy'] = plus_minus(df_pahs['mean_accuracy'],df_pahs['std_accuracy'])
# table['Median Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df_pahs['median_accuracy'],2)]
table['Mean Accuracy [%]'] = plus_minus(df_pahs['mean_accuracy'],
                                    df_pahs['std_accuracy'])
# table['Median Balanced Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df_pahs['median_balanced_accuracy'],2)]

table.T

,0,1,2,3,4,5,6
Model,GNB (U),Poly SVM (U),RBF SVM (U),KNN,GNB (W),Poly SVM (W),RBF SVM (W)
Mean Accuracy [%],91.2 ± 0.6,92 ± 1,95.4 ± 0.5,96.0 ± 0.3,76 ± 1,87.8 ± 0.8,89.2 ± 0.7

In [28]:
df_bsl = pd.read_csv('bsl.csv')

table = pd.DataFrame()

table['Model'] = df_bsl['model']

table['Mean BSL'] = plus_minus(df_bsl['mean_bsl'],
                               df_bsl['std_bsl'])

table.style.hide(axis="index")

In [23]:
df_lit = pd.read_csv('lit_model_comparison.csv')
table = pd.DataFrame()
table['Model'] = df_lit['lit_model']
sigfigs = 2
table['Accuracy [%]'] = [f'{get_right_dec_figs_in_string(np.round(x,sigfigs),sigfigs)}' for x in df_lit['accuracy']]
table['Balanced Accuracy [%]'] = [f'{get_right_dec_figs_in_string(np.round(x,sigfigs),sigfigs)}' for x in df_lit['balanced_accuracy']]
table.T

,0,1,2,3,4,5,6
Model,Zero rule,DBCCR,3D Hybrid,Hybrid (complete),Zero rule (R-U),3D MSCC (R-U),MSCC (R-U)
Accuracy [%],0.85,0.73,0.88,0.35,0.85,0.90,0.35
Balanced Accuracy [%],0.17,0.60,0.78,0.34,0.20,0.84,0.40

In [24]:
# for class-wise accuracies
df_classwise = pd.read_csv('class_wise_accuracy.csv')
table_lm = pd.DataFrame()

comp_classes = [x for x in df_classwise.columns if all(y not in x for y in ['model', 'std', 'median'])]
comp_classes_lm = [x for x in comp_classes if 'phytochemical' not in x]
comp_classes_ru = [x for x in comp_classes if x not in ['lignin','tannin']]

idx_wanted = [i for i, model in enumerate(df_classwise['model']) if all(x not in model for x in ['(U)', 'MSCC', 'R-U'])]
table_lm['Model'] = df_classwise['model'].loc[idx_wanted]

for cclass in comp_classes_lm:
    table_lm[cclass] = plus_minus(df_classwise.loc[idx_wanted][cclass],
                               df_classwise.loc[idx_wanted][f'{cclass}_std'])

table_lm.T

,0,1,5,6,7,8
Model,DBCCR,Hybrid,KNN,GNB (W),Poly SVM (W),RBF SVM (W)
amino_sugar,70 ± 20,70 ± 10,80 ± 10,91 ± 9,90 ± 10,90 ± 10
carbohydrate,40 ± 10,60 ± 10,90 ± 10,92 ± 7,96 ± 5,96 ± 4
lignin,82 ± 5,80 ± 5,67 ± 6,91 ± 3,88 ± 4,89 ± 4
lipid,76 ± 1,89.8 ± 0.7,98.1 ± 0.4,72 ± 2,87.2 ± 0.9,88.3 ± 0.9
peptide,22 ± 5,99 ± 1,94 ± 3,93 ± 3,95 ± 3,95 ± 3
tannin,59 ± 6,59 ± 6,97 ± 3,94 ± 4,99 ± 2,95 ± 5

In [25]:
table_ru = pd.DataFrame()
idx_wanted = [i for i, model in enumerate(df_classwise['model']) if any(x in model for x in ['R-U','MSCC']) and '(U)' not in model]
table_ru['Model'] = df_classwise['model'].loc[idx_wanted]
for cclass in comp_classes_ru:
    table_ru[cclass] = plus_minus(df_classwise.loc[idx_wanted][cclass],
                                  df_classwise.loc[idx_wanted][f'{cclass}_std'])
table_ru.T

,9,13,14,15,16
Model,3D MSCC,KNN (R-U),GNB (W) (R-U),Poly SVM (W) (R-U),RBF SVM (W) (R-U)
amino_sugar,70 ± 20,80 ± 10,93 ± 7,91 ± 9,90 ± 10
carbohydrate,60 ± 10,88 ± 8,91 ± 9,96 ± 5,96 ± 6
lipid,90.1 ± 0.9,98.1 ± 0.4,75 ± 1,88.5 ± 0.9,89.4 ± 0.9
peptide,99 ± 1,94 ± 3,94 ± 3,95 ± 3,95 ± 3
phytochemical,94 ± 3,82 ± 4,99.8 ± 0.4,98 ± 1,97 ± 1

In [26]:
df_classwise = pd.read_csv('class_wise_accuracy_with_pahs.csv')
table_pah = pd.DataFrame()

comp_classes = [x for x in df_classwise.columns if all(y not in x for y in ['model', 'std', 'median'])]
comp_classes_pah = [x for x in comp_classes if 'phytochemical' not in x]

idx_wanted = [i for i, model in enumerate(df_classwise['model']) if all(x not in model for x in ['(U)', 'MSCC', 'R-U'])]
table_pah['Model'] = df_classwise['model'].loc[idx_wanted]

for cclass in comp_classes_pah:
    table_pah[cclass] = plus_minus(df_classwise.loc[idx_wanted][cclass],
                                   df_classwise.loc[idx_wanted][f'{cclass}_std'])

table_pah.T

                       3        4             5            6
Model                KNN  GNB (W)  Poly SVM (W)  RBF SVM (W)
amino_sugar      80 ± 10   94 ± 7        90 ± 7       90 ± 9
carbohydrate      89 ± 8   91 ± 8        97 ± 4       97 ± 4
lignin            67 ± 5   90 ± 4        85 ± 4       88 ± 4
lipid         98.0 ± 0.4   72 ± 2    86.8 ± 0.9   88.4 ± 0.8
pah               88 ± 7   94 ± 6       100 ± 0      100 ± 0
peptide           95 ± 4   94 ± 4        96 ± 3       95 ± 3
tannin            97 ± 4   95 ± 4        99 ± 2       95 ± 4