In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv('model_performance_comparison.csv')
df.columns

Index(['model', 'mean_accuracy', 'std_accuracy', 'median_accuracy',
       'mean_balanced_accuracy', 'std_balanced_accuracy',
       'median_balanced_accuracy', 'mean_chance_balanced_accuracy',
       'std_chance_balanced_accuracy', 'median_chance_balanced_accuracy'],
      dtype='str')

In [42]:
def get_rounding(x:float):
    if x < 1 and x != 0:
        string = str(x)
        string = string.split('.')

        for i in range(len(string[1])):
            if i == len(string[1])-1:
                return i + 1

            elif string[1][i] != '0':
                if int(string[1][i+1]) >= 5 and string[1][i]=='9':
                    return i
                else: return i + 1
    else:
        return -len(str(int(np.round(x,0))))+1

def get_right_dec_figs_in_string(n,dec_places):
    dec_figs = len(str(n).split('.')[1])
    if dec_figs < dec_places:
        return str(n) + ''.join(['0']*(dec_places-dec_figs))
    else:
        return str(n)

def plus_minus(mean,std):
    std_dec_places = [get_rounding(x) if x!=0 else 0 for x in std]

    list_of_strings = []

    for x, y, z in zip(mean,std,std_dec_places):
        if y < 1 and y != 0:
            list_of_strings.append(f'{get_right_dec_figs_in_string(np.round(x,z),z)} ± {get_right_dec_figs_in_string(np.round(y,z),z)}')
        else:
            list_of_strings.append(f'{int(np.round(x,z))} ± {int(np.round(y,z))}')
    
    return list_of_strings

In [57]:
table = pd.DataFrame()

filter = ['(U)' not in x for x in df['model']]

table['Model'] = df[filter]['model']

# table['Mean Accuracy'] = plus_minus(df['mean_accuracy'],df['std_accuracy'])
# table['Median Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_accuracy'],2)]
table['Mean Balanced Accuracy [%]'] = plus_minus(df[filter]['mean_balanced_accuracy'],
                                                 df[filter]['std_balanced_accuracy'])
# table['Median Balanced Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_balanced_accuracy'],2)]

table.T #.style.hide(axis='index')

,0,1,5,6,7,8,9,13,14,15,16
Model,DBCCR,3D Hybrid,kNN,GNB (W),Poly SVM (W),RBF SVM (W),3D MSCC,kNN (R-U),GNB (W) (R-U),Poly SVM (W) (R-U),RBF SVM (W) (R-U)
Mean Balanced Accuracy [%],56 ± 3,82 ± 2,86 ± 2,93 ± 1,95 ± 1,95 ± 1,91 ± 2,90 ± 2,96.8 ± 0.9,97 ± 1,97 ± 1

In [44]:
table = pd.DataFrame()

table['Model'] = df['model']

# table['Mean Accuracy'] = plus_minus(df['mean_accuracy'],df['std_accuracy'])
# table['Median Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_accuracy'],2)]
table['Mean Accuracy [%]'] = plus_minus(df['mean_accuracy'],
                                        df['std_accuracy'])
# table['Median Balanced Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_balanced_accuracy'],2)]

table.T#.style.hide(axis='index')

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
Model,DBCCR,3D Hybrid,GNB (U),Poly SVM (U),RBF SVM (U),kNN,GNB (W),Poly SVM (W),RBF SVM (W),3D MSCC,GNB (U) (R-U),Poly SVM (U) (R-U),RBF SVM (U) (R-U),kNN (R-U),GNB (W) (R-U),Poly SVM (W) (R-U),RBF SVM (W) (R-U)
Mean Accuracy [%],17.51 ± 0.09,99.24 ± 0.03,98.85 ± 0.06,99.56 ± 0.02,99.72 ± 0.01,99.83 ± 0.02,95.8 ± 0.3,99.16 ± 0.06,99.21 ± 0.05,99.29 ± 0.03,98.92 ± 0.04,99.59 ± 0.02,99.76 ± 0.01,99.84 ± 0.01,97.3 ± 0.1,99.25 ± 0.04,99.32 ± 0.04

In [45]:
df_pahs = pd.read_csv('model_performance_comparison_with_pahs.csv')

In [46]:
table = pd.DataFrame()

filter = [True for x in df_pahs['model']]#['(U)' not in x for x in df_pahs['model']]

table['Model'] = df_pahs[filter]['model']

# table['Mean Accuracy'] = plus_minus(df['mean_accuracy'],df['std_accuracy'])
# table['Median Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_accuracy'],2)]
table['Mean Balanced Accuracy [%]'] = plus_minus(df_pahs[filter]['mean_balanced_accuracy'],
                                                 df_pahs[filter]['std_balanced_accuracy'])
# table['Median Balanced Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df['median_balanced_accuracy'],2)]

table.T

,0,1,2,3,4,5,6
Model,GNB (U),Poly SVM (U),RBF SVM (U),kNN,GNB (W),Poly SVM (W),RBF SVM (W)
Mean Balanced Accuracy [%],90 ± 2,60 ± 3,60 ± 3,88 ± 2,93 ± 1,96 ± 1,96.3 ± 0.9

In [47]:
table = pd.DataFrame()

table['Model'] = df_pahs['model']

# table['Mean Accuracy'] = plus_minus(df_pahs['mean_accuracy'],df_pahs['std_accuracy'])
# table['Median Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df_pahs['median_accuracy'],2)]
table['Mean Accuracy [%]'] = plus_minus(df_pahs['mean_accuracy'],
                                    df_pahs['std_accuracy'])
# table['Median Balanced Accuracy'] = [get_right_dec_figs_in_string(x,2) for x in np.round(df_pahs['median_balanced_accuracy'],2)]

table.T

,0,1,2,3,4,5,6
Model,GNB (U),Poly SVM (U),RBF SVM (U),kNN,GNB (W),Poly SVM (W),RBF SVM (W)
Mean Accuracy [%],98.86 ± 0.05,99.68 ± 0.01,99.69 ± 0.01,99.83 ± 0.02,95.8 ± 0.3,99.17 ± 0.04,99.15 ± 0.07

In [48]:
df_bsl = pd.read_csv('bsl.csv')

table = pd.DataFrame()

table['Model'] = [x.replace('Poly', 'Polynomial').replace(' (W)','') for x in df_bsl['model']]

table['Mean BSL'] = plus_minus(df_bsl['mean_bsl'],
                               df_bsl['std_bsl'])

table.style.hide(axis='index')

In [49]:
df_lit = pd.read_csv('lit_model_comparison.csv')
table = pd.DataFrame()
table['Model'] = df_lit['lit_model']
sigfigs = 2
table['Accuracy [%]'] = [f'{get_right_dec_figs_in_string(np.round(x,sigfigs),sigfigs)}' for x in df_lit['accuracy']]
table['Balanced Accuracy [%]'] = [f'{get_right_dec_figs_in_string(np.round(x,sigfigs),sigfigs)}' for x in df_lit['balanced_accuracy']]
table.T

,0,1,2,3,4,5,6
Model,Zero rule,DBCCR,3D Hybrid,Hybrid (complete),Zero rule (R-U),3D MSCC (R-U),MSCC (R-U)
Accuracy [%],0.85,0.73,0.88,0.35,0.85,0.90,0.35
Balanced Accuracy [%],0.17,0.60,0.78,0.34,0.20,0.85,0.40

In [50]:
# for class-wise accuracies
df_classwise = pd.read_csv('class_wise_accuracy.csv')
table_lm = pd.DataFrame()

comp_classes = [x for x in df_classwise.columns if all(y not in x for y in ['model', 'std', 'median'])]
comp_classes_lm = [x for x in comp_classes if 'phytochemical' not in x]
comp_classes_ru = [x for x in comp_classes if x not in ['lignin','tannin']]

idx_wanted = [i for i, model in enumerate(df_classwise['model']) if all(x not in model for x in ['(U)', 'MSCC', 'R-U'])]
table_lm['Model'] = df_classwise['model'].loc[idx_wanted]

for cclass in comp_classes_lm:
    table_lm[cclass] = plus_minus(df_classwise.loc[idx_wanted][cclass],
                               df_classwise.loc[idx_wanted][f'{cclass}_std'])

table_lm.T

,0,1,5,6,7,8
Model,DBCCR,3D Hybrid,kNN,GNB (W),Poly SVM (W),RBF SVM (W)
amino_sugar,71 ± 8,98 ± 3,85 ± 8,100 ± 1,97 ± 4,96 ± 5
carbohydrate,40 ± 10,60 ± 10,80 ± 10,91 ± 7,93 ± 6,94 ± 5
lignin,83 ± 5,82 ± 5,59 ± 6,91 ± 2,90 ± 3,89 ± 3
lipid,82.5 ± 0.4,96.4 ± 0.2,99.65 ± 0.06,81 ± 2,95.9 ± 0.3,96.3 ± 0.3
peptide,2.01 ± 0.06,99.993 ± 0.003,99.97 ± 0.01,99.28 ± 0.06,99.95 ± 0.01,99.93 ± 0.01
tannin,57 ± 7,57 ± 7,93 ± 5,95 ± 4,93 ± 4,96 ± 5

In [52]:
table_ru = pd.DataFrame()
idx_wanted = [i for i, model in enumerate(df_classwise['model']) if any(x in model for x in ['R-U','MSCC']) and '(U)' not in model]
table_ru['Model'] = df_classwise['model'].loc[idx_wanted]
for cclass in comp_classes_ru:
    table_ru[cclass] = plus_minus(df_classwise.loc[idx_wanted][cclass],
                                  df_classwise.loc[idx_wanted][f'{cclass}_std'])
table_ru.T

,9,13,14,15,16
Model,3D MSCC,kNN (R-U),GNB (W) (R-U),Poly SVM (W) (R-U),RBF SVM (W) (R-U)
amino_sugar,98 ± 3,88 ± 8,99 ± 4,97 ± 5,96 ± 6
carbohydrate,60 ± 10,90 ± 10,98 ± 4,97 ± 4,97 ± 4
lipid,96.5 ± 0.2,99.62 ± 0.06,89.0 ± 0.6,96.3 ± 0.2,96.8 ± 0.2
peptide,99.994 ± 0.005,99.968 ± 0.009,99.28 ± 0.06,99.95 ± 0.01,99.92 ± 0.01
phytochemical,93 ± 2,74 ± 6,99.6 ± 0.5,97 ± 1,97 ± 1

In [54]:
df_classwise = pd.read_csv('class_wise_accuracy_with_pahs.csv')
table_pah = pd.DataFrame()

comp_classes = [x for x in df_classwise.columns if all(y not in x for y in ['model', 'std', 'median'])]
comp_classes_pah = [x for x in comp_classes if 'phytochemical' not in x]

idx_wanted = [i for i, model in enumerate(df_classwise['model']) if all(x not in model for x in ['(U)', 'MSCC', 'R-U']) and '(U)' not in model]
table_pah['Model'] = df_classwise['model'].loc[idx_wanted]

for cclass in comp_classes_pah:
    table_pah[cclass] = plus_minus(df_classwise.loc[idx_wanted][cclass],
                                   df_classwise.loc[idx_wanted][f'{cclass}_std'])

table_pah.T

                           3             4             5             6
Model                    kNN       GNB (W)  Poly SVM (W)   RBF SVM (W)
amino_sugar           86 ± 5       100 ± 1        97 ± 3        98 ± 3
carbohydrate         80 ± 10        94 ± 7        97 ± 4        97 ± 4
lignin                58 ± 6        90 ± 4        88 ± 3        87 ± 4
lipid             99.6 ± 0.1        81 ± 1    96.1 ± 0.2    96.0 ± 0.4
pah                   94 ± 6        94 ± 6       100 ± 0       100 ± 0
peptide       99.967 ± 0.009  99.29 ± 0.05  99.92 ± 0.02  99.93 ± 0.02
tannin                95 ± 5        96 ± 5        95 ± 5        96 ± 5